on:
  push:
    branches: [main]

jobs:
  cron:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: python -m venv venv
    - run: venv/bin/pip install -r requirements.txt
    - run: venv/bin/python -um pythonbinary.scrape
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cronwin32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: python -m venv venv
    - run: venv/Scripts/pip install -r requirements.txt
    - run: venv/Scripts/python -um pythonbinary.scrape
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
